name: "issue assign"
description: "A github action written in go"
author: "dhruv jain"

inputs:
  github_token:
    description: "Github token"
    required: true
  
  commands:
    description: "Commands to run"
    required: false
    default: "/assign"

runs:
  using: "node16"
  main: "invoke-binary.js"